apiVersion: v1
kind: Service
metadata:
  name: itay-web
  labels:
    app: itay-web
spec:
  type: LoadBalancer
  selector:
    app: itay-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itay-web
  labels:
    app: itay-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itay-web
  template:
    metadata:
      labels:
        app: itay-web
    spec:
      containers:
      - name: itay-web
        image: itayhaike/itay-web
        ports:
        - containerPort: 80
